### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/PecoRename#11]
There is no link to documentation which could contain help or update log .

**Comment by janus2** [comment]
In the packages from the site, you added in the about window there is a document in en, fr, de, it.
Do you think we should start from there? The app is pretty self-explanatory.

**Comment by humdingerb** [comment]
We could start by importing these documents. Then adjust the english version and point potential translators to the existing old files. Maybe some things can be copied unchanged and saves a bit of work.

I feel that your talents would be wasted on docs. :)
I can do it, if you're not keen on it. I'd go with my standard doc-design that's inspired by the user guide css. I've used it for clipdinger, filer, burnitnow etc.

**Comment by janus2** [comment]
I love those css 👍

**Comment by humdingerb** [comment]
Cool. I already extracted the original docs and will push soon.
Also, saving the columns was indeed easy. Will push that too.

**Comment by humdingerb** [comment]
I'm working on the docs at the moment, and am almost done, BTW.

**Comment by janus2** [comment]
BTW the documentation is awesome!

**Comment by humdingerb** [comment]
Thanks! Took me quite a while, actually. There are always bits and pieces to add or improve. And since the new AboutWindow shows a huuuuge icon, I had to work on making it a bit prettier, too.  The AboutWindow optics need some tweaking...

WRT to central CSS. Maybe there could be "standard_user_doc.css" in /system/documentation/ that apps that choose so, could link in their docs.

**Comment by scottmc** [comment]
any update on the status of this one?

**Comment by humdingerb** [comment]
The PecoRename package comes with documentation, which can be view with a menu item from the app.
Solved, I'd say.
